name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -lF
      - run: ./test.sh
